//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YuzuBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YuzuBot.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157699755590303925/dc_logo.png.
        /// </summary>
        internal static string DCThumnail {
            get {
                return ResourceManager.GetString("DCThumnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;:eligma:1161526665286013000&gt;.
        /// </summary>
        internal static string Emote_Eligma {
            get {
                return ResourceManager.GetString("Emote_Eligma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;:paper_1star:1157724704182902924&gt;.
        /// </summary>
        internal static string Emote_Gacha1Star {
            get {
                return ResourceManager.GetString("Emote_Gacha1Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;:paper_2star:1157724705441189991&gt;.
        /// </summary>
        internal static string Emote_Gacha2Star {
            get {
                return ResourceManager.GetString("Emote_Gacha2Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;:paper_3star:1157724708788244623&gt;.
        /// </summary>
        internal static string Emote_Gacha3Star {
            get {
                return ResourceManager.GetString("Emote_Gacha3Star", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;:pickup_v2:1160600962491220058&gt;.
        /// </summary>
        internal static string Emote_Gacha3StarPickup {
            get {
                return ResourceManager.GetString("Emote_Gacha3StarPickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;:pyroxene:1161527096389144626&gt;.
        /// </summary>
        internal static string Emote_Pyroxene {
            get {
                return ResourceManager.GetString("Emote_Pyroxene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696388990242987/yuzu_a.png.
        /// </summary>
        internal static string YuzuImage_A {
            get {
                return ResourceManager.GetString("YuzuImage_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696389506154596/yuzu_cry.png.
        /// </summary>
        internal static string YuzuImage_Cry {
            get {
                return ResourceManager.GetString("YuzuImage_Cry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696389908811908/yuzu_default.png.
        /// </summary>
        internal static string YuzuImage_Default {
            get {
                return ResourceManager.GetString("YuzuImage_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696390349209620/yuzu_despair.png.
        /// </summary>
        internal static string YuzuImage_Despair {
            get {
                return ResourceManager.GetString("YuzuImage_Despair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696390630215800/yuzu_determined.png.
        /// </summary>
        internal static string YuzuImage_Determined {
            get {
                return ResourceManager.GetString("YuzuImage_Determined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696390932222103/yuzu_fear.png.
        /// </summary>
        internal static string YuzuImage_Fear {
            get {
                return ResourceManager.GetString("YuzuImage_Fear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696391259365426/yuzu_kimo.png.
        /// </summary>
        internal static string YuzuImage_Kimo {
            get {
                return ResourceManager.GetString("YuzuImage_Kimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696391498453012/yuzu_mataku.png.
        /// </summary>
        internal static string YuzuImage_Mataku {
            get {
                return ResourceManager.GetString("YuzuImage_Mataku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696391695581234/yuzu_smile.png.
        /// </summary>
        internal static string YuzuImage_Smile {
            get {
                return ResourceManager.GetString("YuzuImage_Smile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://cdn.discordapp.com/attachments/1157692490099462274/1157696391964004382/yuzu_smile_small.png.
        /// </summary>
        internal static string YuzuImage_SmileSmall {
            get {
                return ResourceManager.GetString("YuzuImage_SmileSmall", resourceCulture);
            }
        }
    }
}
